// Reference-fidelity design system: editorial copy blocks, navy information rail, and tactile cleaning photography.

import { ArrowRight, Check, Clock3, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import SiteFooter, { LocationPanel } from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import PageIntro, { SectionHeading } from "@/components/PageIntro";
import { ConversionBand } from "@/components/ServiceBlocks";
import { MAP_SEARCH_URL, PRIMARY_PHONE, upholsteryImage, whatsappLink } from "@/lib/site";

export default function About() {
  return <div className="site-shell"><SiteHeader /><main id="main-content">
    <div className="container"><PageIntro eyebrow="About us" title={<>A cleaning company built on doing the job <em>properly.</em></>} description="Carlson Cleaning Services is an Accra-based cleaning company offering residential, commercial and specialist cleaning with an agreed scope before every job."><a className="button button--whatsapp" href={whatsappLink()} target="_blank" rel="noreferrer"><MessageCircle size={17} /> Talk to us on WhatsApp</a><Link className="button button--outline-navy" href="/services">Browse our services <ArrowRight size={17} /></Link></PageIntro></div>

    <section className="section section--about-story"><div className="container about-story-grid"><div className="about-story-copy"><p className="eyebrow">Who we are</p><h2>Good cleaning starts with a clear conversation.</h2><p>Carlson Cleaning Services works with households, offices, shops and commercial premises across Accra. Some customers book us for routine upkeep; others call when a space needs a full reset — a move-out deep clean, upholstery that has taken years of use, or a newly built property still covered in construction dust.</p><p>We keep the process straightforward. You tell us the space, we agree the scope, and our team arrives with the right equipment and cleaning agents for the surfaces involved. Where a job needs extra care — fumigation, delicate fabrics, high glass — we explain the preparation and timing in advance.</p><p>Today we offer 15 confirmed services across residential, commercial and specialist cleaning, and we would rather tell you honestly that something falls outside our scope than take on work we cannot do well.</p><div className="about-story-actions"><a className="text-link" href={`tel:${PRIMARY_PHONE.replace(/\s/g, "")}`}><Phone size={16} /> Call {PRIMARY_PHONE}</a><Link className="text-link" href="/contact">Request a quote <ArrowRight size={16} /></Link></div></div><div className="about-story-visual"><img src={upholsteryImage} alt="Carlson cleaner treating upholstery in a home in Accra" /><span className="visual-stamp"><strong>15+</strong><small>confirmed<br />services</small></span></div></div></section>

    <section className="section section--principles"><div className="container"><div className="section-topline"><span className="eyebrow">How we work</span><span>02 / 04</span></div><SectionHeading title="A simple standard, applied carefully." description="The job should feel clear before we arrive and considered while we work." /><div className="principles-grid"><article><ShieldCheck size={24} /><span>01</span><h3>Clear scope, clear price</h3><p>We confirm exactly what will be cleaned and what it costs before the team arrives, so there are no surprises on the day.</p></article><article><Check size={24} /><span>02</span><h3>Briefed, respectful teams</h3><p>Cleaners are briefed on your space and your instructions, and work around occupied homes and offices with care.</p></article><article><Phone size={24} /><span>03</span><h3>One point of contact</h3><p>Call or WhatsApp {PRIMARY_PHONE} and you reach the people who schedule and run the job.</p></article></div></div></section>

    <section className="section section--about-facts"><div className="container about-facts-grid"><div className="about-facts-rail"><div><span>Business</span><strong>Carlson Cleaning Services</strong></div><div><span>Location</span><strong>Martino Residence<br />Accra, Ghana</strong></div><div><span>Enquiries</span><strong>Open 24 hours</strong></div><div><span>Service area</span><strong>Accra and surrounding areas</strong></div></div><div className="about-facts-copy"><p className="eyebrow">Local knowledge, practical service</p><h2>Made for the way Accra lives and works.</h2><p>From occupied homes to busy workspaces, we plan around the people and materials in the room. That is why the first step is always a useful conversation, not a generic package.</p><a className="button button--navy" href={MAP_SEARCH_URL} target="_blank" rel="noreferrer">Find us on Google <ArrowRight size={17} /></a></div></div></section>

    <div className="container"><ConversionBand title="Want to talk through your space?" description="Send the details on WhatsApp and we will help you decide what comes next." primaryLabel="Talk to Carlson" secondaryLabel="See our service areas" /></div>
  </main><SiteFooter /></div>;
}
